StylesPath = styles

Vocab = pdam

MinAlertLevel = suggestion

[formats]
rmd = md
qmd = md

[*.{Rmd, qmd}]
BasedOnStyles = Vale

# Ignore Zenodo DOIs
TokenIgnores = (10\.\d+/[^\s\)\]]+)

[*.R]
BasedOnStyles = Vale   

[NEWS.md]
BasedOnStyles = Vale